version: '3'

services:
  code_style:
    build: docker/code_style
    volumes:
      - .:/src
      - ./code_style.sh:/code_style.sh:ro
      - ./format:/format:ro
    command: ["/bin/bash", "/code_style.sh", "/src"]
