name: sanitizer-tests-clang
on:
  push:
    paths:
      - CMakeLists.txt
      - libtransmission/**
      - tests/**
      - utils/**
  pull_request:
    types: [opened, reopened]
    paths:
      - CMakeLists.txt
      - libtransmission/**
      - tests/**
      - utils/**
env:
  GTEST_OUTPUT: xml:./
jobs:
  sanitizer-tests-clang:
    uses: ./.github/workflows/sanitizer-tests.yml
    with:
      c: clang
      cxx: clang++
      compiler_package_name: clang
      sanitizers: address,leak,undefined
