name: sanitizer-test-clang
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
env:
  GTEST_OUTPUT: xml:./
jobs:
  sanitizer-test-clang:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Source
        id: get-source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: src
          submodules: recursive
      - name: Check for diffs that affect tests
        id: do-diffs-affect-tests
        run: |
          set +e
          git -C "${GITHUB_WORKSPACE}/src" diff --exit-code origin/main -- CMakeLists.txt libtransmission tests third-party utils
          echo "::set-output name=changed::$?"
          set -e
      - name: Get Deps
        id: get-deps
        if: (steps.do-diffs-affect-tests.outputs.changed == '1') || (github.event_name == 'push' && github.ref_name == 'main')
        run: |
          set -ex
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            clang \
            cmake \
            gettext \
            libcurl4-openssl-dev \
            libdeflate-dev \
            libevent-dev \
            libfmt-dev \
            libminiupnpc-dev \
            libnatpmp-dev \
            libpsl-dev \
            libssl-dev \
            ninja-build
      - name: Configure
        id: configure
        if: (steps.do-diffs-affect-tests.outputs.changed == '1') || (github.event_name == 'push' && github.ref_name == 'main')
        run: |
          cmake \
            -S src \
            -B obj \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_COMPILER='clang++' \
            -DCMAKE_CXX_FLAGS='-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,leak,undefined' \
            -DCMAKE_C_COMPILER='clang' \
            -DCMAKE_C_FLAGS='-gdwarf-4 -fno-omit-frame-pointer -fsanitize=address,leak,undefined' \
            -DCMAKE_INSTALL_PREFIX=pfx \
            -DENABLE_CLI=OFF \
            -DENABLE_GTK=OFF \
            -DENABLE_QT=OFF \
            `#-DENABLE_WEB=ON`
      - name: Make
        id: make
        if: (steps.do-diffs-affect-tests.outputs.changed == '1') || (github.event_name == 'push' && github.ref_name == 'main')
        run: cmake --build obj --config Debug --target libtransmission-test transmission-show
      - name: Test with sanitizers
        id: test
        if: (steps.do-diffs-affect-tests.outputs.changed == '1') || (github.event_name == 'push' && github.ref_name == 'main')
        run: cmake -E chdir obj ctest --build-config Debug --output-on-failure
