name: Mirror main to 4.1 branch

on:
  push:
    branches:
      - 'main'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Mirror changes to 4.1 branch
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create PR
        id: pull
        uses: tretuna/sync-branches@1.4.0 # https://github.com/marketplace/actions/sync-branches
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: 'main'
          TO_BRANCH: 'dev/4-1-0'
          CONTENT_COMPARISON: true
  label_issues:
    needs: sync-branches
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["automerge"]
            })
  merge:
    needs: label_issues
    runs-on: ubuntu-latest
    name: Automatically merge PR
    steps:
    - name: Integration check
      uses: squalrus/merge-bot@v0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: false
        reviewers: false
        labels: automerge
        blocking_labels: do not merge
        checks_enabled: false
        method: merge
        delete_source_branch: false