name: Mirror main to 4.1 branch

on:
  push:
    branches:
      - 'main'

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: sync-branches
      uses: repo-sync/github-sync@v2
      with:
        source_branch: "main"
        destination_branch: "dev/4-1-0"
        github_token: ${{ secrets.GITHUB_TOKEN }}